name: 'Sync Remote File with Local File'
description: 'Synchronized Remote File with Local File Up-to-Date'
inputs:
  url:
    description: 'The url of the file to download'
    required: true
  file_in_repo:
    description: 'The location of the file in the repository to update if changed'
    required: true
  git_user:
    description: 'The name of the git user'
    required: true
    default: 'rubencom/sync-remote-file-with-local-file-docker-action'
  git_email:
    description: 'The email of the git user'
    required: true
    default: 'no-reply@github.com'
outputs:
  status:
    description: 'If the file has changed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.file_in_repo }}
    - ${{ inputs.git_user }}
    - ${{ inputs.git_email }}
